name: Build quip-minimal Docker Image

on: [ push ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Pull the latest version of the image
    # in order to use unchanged layers
    - name: pull last version of image
      run: docker pull libatomsquip/quip-minimal:latest || true

    - name: Build the Docker image
      run: docker build --tag libatomsquip/quip-minimal:latest --cache-from libatomsquip/quip-minimal quip-minimal-docker

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push to Docker Hub
      run: docker push libatomsquip/quip-minimal:latest

